---
title: "Final Report Essentials"
author: "Jeremy Springman"

institute: "University of Pennsylvania"
date: last-modified
toc: true

bibliography: references.bib

format: 
  html:
    self-contained: true

editor: source
---



```{r }
#| include: false
#| warning: false
#| message: false

library(ggplot2)
library(readr)
library(ggdag)
library(tidyverse)
library(gt)
library(modelsummary)

# read-in data
dat = read_csv(here::here("workshops/aau_survey/clean_endline_did.csv") ) %>%
    # clean home region variable
  mutate(q8_baseline = ifelse(q8_baseline == "Southern Nations, Nationalities, and Peoples Region", "SNNPR", q8_baseline), 
         q8_baseline = str_remove(q8_baseline, " Region"))
# create color palette for plotting
palette = MetBrewer::met.brewer(name = "Cross")




```




### Additive Scale

```{r}
#| echo: false
#| warning: false

## Find participation measures that are based on a count
add_ecols = grep("q13_4_1$|q13_5_1$", names(dat), value = T)

dat = dat %>%
  #mutate(add_participation_end =  rowSums(across(add_ecols), na.rm = T) )
  mutate(add_participation_end =  rowSums(across(add_ecols) ) )

#dat$add_participation_end = dat$q13_4_1 + dat$q13_5_1



```

### Averaged Z-Scores

**When to use z-scores**

- When

```{r}
#| echo: false
#| warning: false

## Subsetting baseline and endline columns for Z-score

bcols = grep("^q13_.*_baseline$", names(dat), value = T)
ecols = grep("^q13_\\d_\\d$", names(dat), value = T)









# participation
participate = dat %>% 
  select(`Attend meeting` = q13_1_baseline, 
         `Protest` = q13_2_baseline, 
         `NGO event` = q13_3_baseline, 
         `Signed petition` = q13_4_baseline, 
         `Contact official` = q13_5_baseline, 
         `Contact student representative` = q13_6_baseline, 
         `Contact an NGO` = q13_7_baseline) %>% 
  drop_na() %>% 
  pivot_longer(everything()) %>% 
  group_by(name, value) %>% 
  tally() %>% 
  mutate(pct = n/sum(n)) %>% 
  mutate(value = fct_relevel(value, "Never", after = Inf), 
         value = fct_rev(value))



ggplot(participate %>% filter(!name %in% unique(participate$name)[c(2,3,6)]), aes(x = value, y = pct)) + 
  geom_col(fill = palette[9]) + 
  facet_wrap(vars(name), scales = "free") + 
  scale_y_continuous(labels = scales::percent) +
  labs(y = "Percent of respondents", x = NULL, 
       title = "How do youth participate?", 
       subtitle = glue::glue("Number of respondents = {scales::comma(sum(participate$n)/7)}"), 
       caption = "See paper for full question wording") + 
  scale_x_discrete(labels = scales::label_wrap(10))

ggplot(participate %>% filter(name %in% unique(participate$name)[c(2,3,6)]), aes(x = value, y = pct)) + 
  geom_col(fill = palette[9]) + 
  facet_wrap(vars(name), scales = "free", ncol=2) + 
  scale_y_continuous(labels = scales::percent) +
  labs(y = "Percent of respondents", x = NULL, 
       title = "How do youth participate?", 
       subtitle = glue::glue("Number of respondents = {scales::comma(sum(participate$n)/7)}"), 
       caption = "See paper for full question wording") + 
  scale_x_discrete(labels = scales::label_wrap(10))

```



### Principal Component Analysis



## Describing the Sample



### Demographics


```{r }
#| echo: false
#| warning: false

## demographics
demos = dat %>%
  drop_na(q3_baseline) %>% 
  select(`Respondent Gender` = q3_baseline, `Work as a student?` = q4_baseline, 
         `Rural or urban?` = q5_baseline, `Financial support from family?` = q6_baseline, 
         `Home region` = q8_baseline,
         `Student Year` = class_year) %>% 
  pivot_longer(everything()) %>% 
  group_by(name, value) %>% 
  tally() %>% 
  mutate(pct = n/sum(n)) %>% 
  top_n(n = 5, wt = pct)

demos$name = factor(demos$name, levels = c('Home region', 'Rural or urban?', 'Student Year', 'Respondent Gender', 'Work as a student?', 'Financial support from family?'))


ggplot(demos , aes(y = value, x = pct)) + 
  geom_col(fill = palette[9]) + 
  facet_wrap( ~name, scales = "free") + 
  scale_y_discrete(labels = scales::label_wrap(30)) + 
  hrbrthemes::scale_x_percent(limits = c(0, 1)) + 
  labs(x = "Percent of respondents", y = NULL, 
       title = "Demographic characteristics of baseline respondents", 
       subtitle = glue::glue("Number of respondents = {scales::comma(nrow(df))}"), 
       caption = "Note: home region only displays top five categories by size.")

```

### Levels of Engagement

```{r}
#| echo: false
#| warning: false


# participation
participate = dat %>% 
  select(`Attend meeting` = q13_1_baseline, 
         `Protest` = q13_2_baseline, 
         `NGO event` = q13_3_baseline, 
         `Signed petition` = q13_4_baseline, 
         `Contact official` = q13_5_baseline, 
         `Contact student representative` = q13_6_baseline, 
         `Contact an NGO` = q13_7_baseline) %>% 
  drop_na() %>% 
  pivot_longer(everything()) %>% 
  group_by(name, value) %>% 
  tally() %>% 
  mutate(pct = n/sum(n)) %>% 
  mutate(value = fct_relevel(value, "Never", after = Inf), 
         value = fct_rev(value))



ggplot(participate %>% filter(!name %in% unique(participate$name)[c(2,3,6)]), aes(x = value, y = pct)) + 
  geom_col(fill = palette[9]) + 
  facet_wrap(vars(name), scales = "free") + 
  scale_y_continuous(labels = scales::percent) +
  labs(y = "Percent of respondents", x = NULL, 
       title = "How do youth participate?", 
       subtitle = glue::glue("Number of respondents = {scales::comma(sum(participate$n)/7)}"), 
       caption = "See paper for full question wording") + 
  scale_x_discrete(labels = scales::label_wrap(10))

ggplot(participate %>% filter(name %in% unique(participate$name)[c(2,3,6)]), aes(x = value, y = pct)) + 
  geom_col(fill = palette[9]) + 
  facet_wrap(vars(name), scales = "free", ncol=2) + 
  scale_y_continuous(labels = scales::percent) +
  labs(y = "Percent of respondents", x = NULL, 
       title = "How do youth participate?", 
       subtitle = glue::glue("Number of respondents = {scales::comma(sum(participate$n)/7)}"), 
       caption = "See paper for full question wording") + 
  scale_x_discrete(labels = scales::label_wrap(10))

# obstacles
obstacle = dat %>% 
  select(`Lack of resources` = q14_1, 
         `Fear of judgment` = q14_2, 
         `Fear of consequences` = q14_3, 
         `Lack of interest` = q14_4, 
         `Lack of information` = q14_5) %>% 
  drop_na() %>% 
  pivot_longer(everything()) %>% 
  group_by(name, value) %>% 
  tally() %>% 
  mutate(pct = n/sum(n)) %>% 
  mutate(value = fct_relevel(value, "Never", after = Inf), 
         value = fct_rev(value))



ggplot(obstacle, aes(x = value, y = pct)) + 
  geom_col(fill = palette[9]) + 
  facet_wrap(vars(name), scales = "free") + 
  scale_y_continuous(labels = scales::percent) +
  labs(y = "Percent of respondents", x = NULL, 
       title = "How often do obstacles prevent participation?", 
       subtitle = glue::glue("Number of respondents = {scales::comma(sum(obstacle$n)/5)}"), 
       caption = "See paper for full question wording") + 
  scale_x_discrete(labels = scales::label_wrap(10))



# current roles
role = dat %>% 
  select(`Religious group` = q15_1, 
         `Ethnic/culture group` = q15_2, 
         `Political group` = q15_3, 
         `Voluntary organization` = q15_4) %>% 
  drop_na() %>% 
  pivot_longer(everything()) %>% 
  group_by(name, value) %>% 
  tally() %>% 
  mutate(pct = n/sum(n)) %>% 
  mutate(value = fct_relevel(value, "Official leader", after = 0L))



ggplot(role, aes(x = value, y = pct)) + 
  geom_col(fill = palette[9]) + 
  facet_wrap(vars(name), scales = "free") + 
  scale_y_continuous(labels = scales::percent) +
  labs(y = "Percent of respondents", x = NULL, 
       title = "Is respondent involved in the following...", 
       subtitle = glue::glue("Number of respondents = {scales::comma(sum(role$n)/4)}"), 
       caption = "See paper for full question wording") + 
  scale_x_discrete(labels = scales::label_wrap(10))


```


## Results


```{r}
#| echo: false
#| warning: false

dat = dat %>%
  mutate(moved = case_when(q8_baseline == "Addis Ababa" ~ 0, TRUE ~ 1) )

#table(dat$q8_baseline, dat$moved)

models <- list()
models[['Contact Official']] = lm(q13_4_1 ~ moved, dat)
models[['Attend Meeting']] = lm(q13_1_1 ~ moved, dat)
models[['NGO Volunteer']] = lm(q13_8_1 ~ moved, dat)
models[['Sign Petition']] = lm(q13_5_1 ~ moved, dat)

modelsummary(
  models,
  estimate  = "{estimate}{stars} ({std.error})",
             statistic = NULL,
  gof_omit = 'IC|RMSE|Log|F|R2$|Std.')

```


