---
title: "R, RStudio, and Quarto"
date: 2025-01-29
---


## Required Readings

- None

## Assignment

- Install RStudio
  + [Instructions](/assignments/install-R.html)
- Install [Quarto](https://quarto.org/docs/get-started/hello/rstudio.html)
  + [Instructions](/assignments/01_quarto.html)


## Materials

Please download the *R Tutorial Source* script using the link below. I will be using the *R Tutorial Source* file (.qmd) to lead the session. The *R Tutorial Visual* contains a link to a rendered version of the *R Tutorial Source* that you can open as an .html document in your web browser. If you prefer, you can copy and paste code from the html file into RStudio.

- [R + Quarto Slides](/slides/05_quarto.html)
- [R Tutorial Source (.qmd)](https://github.com/jrspringman/psci3200-globaldev/blob/main/workshops/w1_quarto.qmd)
- [R Tutorial Visual (.html)](/workshops/w1_quarto.html)
- [Data](https://github.com/jrspringman/psci3200-globaldev/blob/main/workshops/aau_survey/clean_endline_did.csv)
- [Github Slides](/slides/lees-git.html)

I will be using a  file (.qmd) to lead the session. Quarto is a specific type of file in RStudio that integrates code into document production. Quarto can be useful for producing .pdf or .html files that to share the results of data analysis with donors and policymakers. If you would like to install Quarto, please consult the materials below:






